### ISSUE TITLE
Missing "add" in the node expression

### ISSUE THREAD

**Issue by Fusezion** [SkyCraft78/skript-storage#2]
## Enhancement Request

As it stands unlike skript-yaml there's currently no way in-game to add a new value to a list of values in a file
while looking at the code I noticed you only support "set", "remove all" and "remove" but no "add" or even a way to "clear"/"delete" a single node within the file

### Reasoning to add

Without the ability to "add" new values to a list of stuff it makes it much harder to create an ingame config without just making editing the file easier *which by default always will be*

**Comment by SkyCraft78** [comment]
Thank you for this idea, I'll start working on it this afternoon :)

**Comment by SkyCraft78** [comment]
I'm back;
When used with a list mark: `add "hello" to values "key" of "config"`, it will add (or remove, it works here too) the value to the list.
When used with a single mark: `add 1 to value "key" of "config"`, it will add the number itself to the current number value.
If the specified key is not a number, skript-storage will simply throw an exception (user-friendly exception)
I hope it will complete all of what you asked for, feel free to re-open this issue if you have further requests ^^
